export type ResumeTemplateCatalogItem = {
    id: string;
    name: string;
};

export const RESUME_TEMPLATE_CATALOG: ResumeTemplateCatalogItem[] = [
    { id: "classic", name: "Classic" },
    { id: "modern", name: "Modern Teal" },
    { id: "professional", name: "Professional" },
    { id: "minimal", name: "Minimal" },
    { id: "executive", name: "Executive" },
    { id: "tech", name: "Tech / ATS" },
    { id: "sidebar-teal", name: "Teal Flow" },
    { id: "sidebar-navy", name: "Navy Pro" },
    { id: "emerald", name: "Emerald Clean" },
    { id: "ats", name: "Pure ATS" },
    { id: "faang-focus", name: "FAANG Focus" },
    { id: "maang-slate", name: "MAANG Slate" },
    { id: "platform-prime", name: "Platform Prime" },
    { id: "recruiter-scan", name: "Recruiter Scan" },
    { id: "sde-compact", name: "SDE Compact" },
    { id: "pulse-red", name: "Pulse Red" },
    { id: "skyline-blue", name: "Skyline Blue" },
    { id: "copper-exec", name: "Copper Exec" },
    { id: "column-mint", name: "Column Mint" },
    { id: "midnight-rail", name: "Midnight Rail" },
    { id: "amber-rail", name: "Amber Rail" },
    { id: "briefing-slate", name: "Briefing Slate" },
    { id: "signal-indigo", name: "Signal Indigo" },
    { id: "vector-green", name: "Vector Green" },
    { id: "atlas-grid", name: "Atlas Grid" },
    { id: "quartz-frame", name: "Quartz Frame" },
    { id: "summit-panels", name: "Summit Panels" },
    { id: "mono-ats-plus", name: "Mono ATS Plus" },
    { id: "ledger-ats", name: "Ledger ATS" },
    { id: "precision-ats", name: "Precision ATS" },
    { id: "harbor-profile", name: "Harbor Profile" },
    { id: "zenith-stack", name: "Zenith Stack" },
    { id: "cobalt-timeline", name: "Cobalt Timeline" },
    { id: "sage-brief", name: "Sage Brief" },
    { id: "linen-column", name: "Linen Column" },
    { id: "sterling-chronicle", name: "Sterling Chronicle" },
    { id: "vertex-hybrid", name: "Vertex Hybrid" },
    { id: "opal-direct", name: "Opal Direct" },
    { id: "summit-signal", name: "Summit Signal" },
    { id: "civic-outline", name: "Civic Outline" },
    { id: "atlas-brief", name: "Atlas Brief" },
    { id: "northstar-ledger", name: "Northstar Ledger" },
    { id: "meridian-profile", name: "Meridian Profile" },
    { id: "forged-ats", name: "Forged ATS" },
    { id: "clarity-grid", name: "Clarity Grid" },
    { id: "quorum-compact", name: "Quorum Compact" },
    { id: "elevate-column", name: "Elevate Column" },
    { id: "horizon-split", name: "Horizon Split" },
    { id: "anchor-clean", name: "Anchor Clean" },
    { id: "pinnacle-flow", name: "Pinnacle Flow" },
];
